### ISSUE TITLE
[Mariadb-Master-Slave]Triển khai test case ON/OFF

### ISSUE THREAD

**Issue by bachkhoabk47** [VietOpenCPS/deploy#13]
- Master Off
  - Test với  trường hợp tắt node master, sau vài giây bật lại  
  - Insert và update một số bản ghi và kiểm tra sự đồng bộ giữa 2 nodes
- Slave Off
  - Test với  trường hợp tắt node slave, sau vài giây bật lại  
  - Insert và update một số bản ghi và kiểm tra sự đồng bộ giữa 2 nodes  
    ( Viết script để đẩy dữ liệu insert vào database với khoảng 1000 bản ghi khác nhau )

**Comment by tuhoanganh** [comment]
- Master Off
  - Tạo một Table mới trong database Opencps man tên TEST, insert vài bản ghi đơn giản => Slave đồng bộ bình thường.
  - Tắt node master, trên Slave show slave status thì thấy lỗi không kết nối được đến Node Master.
  - Sau 5 phút, khởi động lại Node Server.
  - Insert và update 1000 bản ghi vào table TEST trong database OpenCPS => Slave kết nối được và tiếp tục đồng bộ.
- Slave Off
  - Tạo Script đơn giản để insert 2000 bản ghi vào Node Master và chạy.
  - Trong quá trình chạy, đột ngột tắt Node Slave.
  - Sau khi Script chạy xong, Bật lại Node Slave. 
  - Node Slave tiếp tục đồng bộ bình thường

Ví dụ:

```
for i in {1..2000}; do
mysql -uroot -p$pass -e "use opencps; INSERT INTO test (id, name) VALUES ($i, 'test');"
done
```
