### ISSUE TITLE
[Mariadb-Master-Slave] Đổi Slave thành master

### ISSUE THREAD

**Issue by bachkhoabk47** [VietOpenCPS/deploy#14]
- Gỉa lập Master bị hỏng, ví dụ bị hỏng ổ cứng, rút dây mạng, dừng dịch vụ, ....  
- Chuyển node slave thành node master tạm thời  
- Sau khi dựng lại node master cũ, đưa node master cũ trở về master, node master tạm thời trở lại về node slave

**Comment by tuhoanganh** [comment]
- Master hỏng và không thể khôi phục hoạt động.
- Chuyển Node Slave thành Node Master bằng cách
  - Vào file /etc/my.cnf bỏ dòng read-only=1
  - Đăng nhập vào Slave Database và xóa cấu hình slave cũ bằng câu lệnh
  
  ```
  stop slave;
  reset slave all;
  ```
  - Reset mariaDB service
  
  ```
  systemctl restart mysql
  ```
  - Trỏ app về địa chỉ IP của Master tạm thời đó.
  - Hệ thống tiếp tục hoạt động bình thường
- Khi Master cũ đã sẵn sàng hoạt động, trả lại Role Master cho Server đó bằng cách
  - Vào Master tạm thời, dump lại database đồng bộ để đảm bảo không mất mát dữ liệu ra file backup.sql
  - Import backup.sql vào Master cũ và lấy các thông số về Master_log_file và master_log_pos
  - Master tạm thời lại chuyển thành slave bằng việc set read-only trong file /etc/my.cnf và chạy các câu lệnh
  
  ```
  change master to master_host='192.168.10.xxx',
  master_user='slave',
  master_password='XXXXXXX',
  master_port=3306,
  master_log_file='master-bin.00000x',
  master_log_pos=xxx,
  master_connect_retry=10;
  
  start slave;
  ```
  - Sau khi xong, kiểm tra lại trên slave Database bằng câu lệnh
  
  ```
  show slave status\G;
  ```
  - Thử insert vài bản ghi trên Master để kiểm tra.
