### ISSUE TITLE
Create "latest" tag

### ISSUE THREAD

**Issue by tuanta** [VietOpenCPS/deploy#2]
Docker from release 1.3 uses "latest" tag for default pulling: https://github.com/docker/docker-registry/issues/637
We need to create that tag in our Docker Hub.

**Comment by bachkhoabk47** [comment]
Using the command bellow while building a docker image from Dockerfile:
#docker build -t test:0.1 -t test:latest .

**Comment by tuanta** [comment]
> Using the command bellow while building a docker image from Dockerfile:
> #docker build -t test:0.1 -t test:latest .

I have not tried this yet. However, you must update this kind of instructions to README.

**Comment by bachkhoabk47** [comment]
> I have not tried this yet. However, you must update this kind of instructions to README. 

Well, I've updated the Readme file already. :)

**Comment by tuanta** [comment]
> Well, I've updated the Readme file already.

Please put that commit id here and close the ticket.

**Comment by bachkhoabk47** [comment]
Well done. So need to close the ticket.
