### ISSUE TITLE
Tài liệu hóa các Issues của MariaDB Master-Slave

### ISSUE THREAD

**Issue by tuhoanganh** [VietOpenCPS/deploy#21]
Cần tạo thêm một thư mục Test Case trong MariaDB Master-Slave và tài liệu hóa các Test Case để sau này người dùng hoặc cộng đồng có thể review.
Trong thư mục đó sẽ có các file:
- Tên file : Tên test case.
- Mô tả: Mô tả trường hợp của test case xảy ra.
- Các bước xử lý khi gặp sự cố.
- Kết quả.

@vuthao Anh cho em ý kiến về việc tạo file này là file gì nhé? .sh hay .md như readme.

**Comment by vuthao** [comment]
Theo mình cái này nên đặt: Tên test case.md

**Comment by tuhoanganh** [comment]
@vuthao 
Em đã tạo review về Test Case trong Wiki vì như thế sẽ thuật tiện cho việc tham khảo.
Link: https://github.com/VietOpenCPS/deploy/wiki/Tri%E1%BB%83n-khai-c%C3%A1c-Test-Case-cho-MariaDB-Master---Slave
