### ISSUE TITLE
Tìm và đóng gói bản liferay + Jboss chuẩn 

### ISSUE THREAD

**Issue by bachkhoabk47** [VietOpenCPS/deploy#25]
Hiện tại bản Liferay 6.2 và Jboss 7.1.3 đang có một số vấn đề nên sẽ cần phải tìm cách và đóng gói thành một bản lirefay và jboss chuẩn. 
- Phối hợp với đội Dev (a Khoa) để đưa ra được một bản liferay + jboss chuẩn
- Lưu ý những thay đổi trong các file cấu hình của bản đóng gói mới so với các phiên bản trước, ...

**Comment by tuhoanganh** [comment]
Hôm trước, ngay sau buổi họp của nhóm Infra, mình đã làm việc với đội Dev và được cung cấp một bản liferay jboss 7.1.1 official 
Nhưng hiện tại khi OpenCPS lên phiên bản 1.3 có sự thay đổi, thêm mới về việc build file war nên để xác định được phiên bản liferay jboss trên có chuẩn để chạy OpenCPS 1.3 hay xảy ra lỗi hay không thì mình cần phải hoàn thành được việc thay đổi trong quá trình build file war (nội trong sáng nay)
Nếu có lỗi mình sẽ update ở đây và tiếp tục làm việc với đội dev để yêu cầu trợ giúp.

**Comment by tuhoanganh** [comment]
Hiện tại phiên bản sử dụng để triển khai OpenCPS là phiên bản Liferay-portal-jboss-6.2-ce-ga6 trên Sourceforge của liferay, chỉ cần chỉnh sửa một vài cấu hình trong file standalone.xml là có thể deploy.
Quy trình build file war và cấu hình Liferay sẽ được viết trong wiki đồng thời viết bash script để sử dụng cho việc triển khai tự đông cũng như sử dụng cho docker.

Liferay bundled with JBoss: https://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.2.5%20GA6/liferay-portal-jboss-6.2-ce-ga6-20160112152609836.zip/download

**Comment by tuhoanganh** [comment]
Quy trinh triển khai OpenCPS từ source code đã được viết lên wiki tại
https://github.com/VietOpenCPS/deploy/wiki/Quy-tr%C3%ACnh-tri%E1%BB%83n-khai-OpenCPS-t%E1%BB%AB-source-code
