### ISSUE TITLE
Tài liệu hướng dẫn cài đặt MariaDB theo mô hình Master/Slave

### ISSUE THREAD

**Issue by latuannetnam** [VietOpenCPS/deploy#4]
Yêu cầu: 
- Tài  liệu hướng dẫn chi tiết các bước cài đặt MariaDB theo mô hình Master/Slave. 
- Môi trường triển khai: CentOS 7
- Đưa lên Wiki của team Infra tại VietOpenCPS/deploy

**Comment by vuthao** [comment]
@tuhoanganh  mình đã tạo luôn ở đây nhé:
https://github.com/VietOpenCPS/deploy/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-MariaDB-theo-m%C3%B4-h%C3%ACnh-Master-Slave
Bạn copy nội dung lên rồi chỉnh sửa dần.

**Comment by tuhoanganh** [comment]
@vuthao Em đã Upload hướng dẫn cài đặt vào Wiki rồi anh nhé.
