### ISSUE TITLE
Script cài đặt MariaDB theo mô hình Master/Slave

### ISSUE THREAD

**Issue by latuannetnam** [VietOpenCPS/deploy#5]
Yêu cầu:
- Shell script thực hiện cài đặt MariaDB theo mô hình Master/Slave
- Môi trường cài đặt: CentOS 7
- Đưa script lên Github của team tại VietOpenCPS/deploy

**Comment by vuthao** [comment]
Đường dẫn đến file https://github.com/VietOpenCPS/deploy/blob/master/MariaDB_Master_Slave/opencps.sql  không đúng.
@tuhoanganh cần lấy link bằng cách click vào nút Raw.

Do file SQL lớn (10 MB) nên theo mình nên zip file sql này lại để quá trình download được nhanh, sau đó trên script cài đặt mới giản nén nó ra.

**Comment by tuhoanganh** [comment]
- Đã Upload hướng dẫn cài đặt thủ công trên CentOS 7
- Đã Upload Script Tự động cài đặt MariaDB Master-Slave trên CentOS 7
- Đã zip file open.sql sang định dạng tar.gz (1MB) 
- Đã sửa lại đường dẫn đến file opencps.sql (nay là file tar.gz) trong hướng dẫn cài đặt Master-Slave
  Mọi người có thể vào sử dụng, nếu có lỗi hay cần thay đổi gì em sẽ sửa tiếp
  @vuthao @bachkhoabk47 @latuannetnam @hainthl
