### ISSUE TITLE
Script và hướng dẫn cài đặt OpenCPS bằng Docker theo mô hình All-in-one

### ISSUE THREAD

**Issue by latuannetnam** [VietOpenCPS/deploy#6]
Yêu cầu:
- Viết script để người dùng có thể tự cài OpenCPS bằng Docker.
- Script cho Linux: tự động detect OS và command riêng cho từng OS: Ubuntu, Fedora, CentOS
- Mô hình đóng gói: All-in-one, bao gồm cả Liferay + MariaDB trên cùng 1 container
- Viết tài liệu hướng dẫn cách sử dụng script trên Wiki

**Comment by bachkhoabk47** [comment]
# Các công việc đã hoàn thành

> Viết script để người dùng có thể tự cài OpenCPS bằng Docker
> Script cho Linux: tự động detect OS và command riêng cho từng OS: Ubuntu, Fedora, CentOS
> Mô hình đóng gói: All-in-one, bao gồm cả Liferay + MariaDB trên cùng 1 container
>  Viết tài liệu hướng dẫn cách sử dụng script trên Wiki
- Thông tin được cập nhật tại đường dẫn:  
  https://github.com/VietOpenCPS/deploy/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-tri%E1%BB%83n-khai-%E1%BB%A9ng-d%E1%BB%A5ng-OpenCPS-Offline-cho-ng%C6%B0%E1%BB%9Di-d%C3%B9ng-theo-m%C3%B4-h%C3%ACnh-all-in-one,-t%E1%BA%A5t-c%E1%BA%A3-%C4%91%C3%B3ng-g%C3%B3i-trong-m%E1%BB%99t-container

# Các công việc còn tồn đọng

> Script cho Windows

**Comment by latuannetnam** [comment]
Hải test nhé.

**Comment by bachkhoabk47** [comment]
Đã tested

**Comment by hoanganhkg0003** [comment]
Cho mình hỏi khi mình cài xong làm sao vào dc admin
