### ISSUE TITLE
Script và hướng dẫn cài đặt OpenCPS bằng Docker theo mô hình 2 container

### ISSUE THREAD

**Issue by latuannetnam** [VietOpenCPS/deploy#7]
Yêu cầu:
- Viết script để người dùng có thể tự cài OpenCPS bằng Docker.
- Script cho Linux: tự động detect OS và command riêng cho từng OS: Ubuntu, Fedora, CentOS
- Mô hình đóng gói: 2 containers, 1 cho Liferay và 1 cho  MariaDB
- Viết tài liệu hướng dẫn cách sử dụng script trên Wiki

**Comment by bachkhoabk47** [comment]
# Các công việc đã hoàn thành

> Viết script để người dùng có thể tự cài OpenCPS bằng Docker
> Script cho Linux: tự động detect OS và command riêng cho từng OS: Ubuntu, Fedora, CentOS
> Mô hình đóng gói: 2 containers, 1 cho Liferay và 1 cho MariaDB
>  Viết tài liệu hướng dẫn cách sử dụng script trên Wiki
- Thông tin được cập nhật tại đường dẫn:  
  https://github.com/VietOpenCPS/deploy/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-tri%E1%BB%83n-khai-%E1%BB%A9ng-d%E1%BB%A5ng-OpenCPS-Offline-cho-ng%C6%B0%E1%BB%9Di-d%C3%B9ng-m%C3%B4-h%C3%ACnh-ch%E1%BA%A1y-2-container

# Các công việc còn tồn đọng

> Script cho Windows

**Comment by latuannetnam** [comment]
Hải test script nhé.

**Comment by hainthl** [comment]
Hướng dẫn thêm phần phải chạy với quyền root
- Phần hỏi có đè không thì phần y/n để tách ra và thêm vào hướng dẫn
- Thư mục download về nên cá nhân hóa của opencps nếu không sẽ bị đè (hiện mặc định là docker-compose

```
docker-compose installed, so go to next step
Version Ubuntu > 14.10, this just needs
/home/hai/docker-compose
Folder exists. Please type y for overried folder.</br>y/ny
You enteredi: y
A    docker-compose
A    docker-compose/.gitignore
A    docker-compose/Makefile
A    docker-compose/docker-compose.yml
A    docker-compose/mariadb-init-data
A    docker-compose/mariadb-init-data/opencps10_20160518.sql
A    docker-compose/mariadb-mycnf
A    docker-compose/mariadb-mycnf/my.cnf
A    docker-compose/shell
Exported revision 109.
Creating dockercompose_mariadb_1
Creating dockercompose_liferay_1
sh: 0: -c requires an argument
Done! You can open browser with the address: localhost:8080 for testing application. Thanks

Kiểm tra lại hướng dẫn https://github.com/VietOpenCPS/deploy/tree/master/opencps-dockerize/dockerize-all-in-two-containers
Chạy xong vào localhost:8080 không thấy chạy 

```

`

`

**Comment by bachkhoabk47** [comment]
Đã xử lý xong theo yêu cầu.

> Phần hỏi có đè không thì phần y/n để tách ra và thêm vào hướng dẫn
> Thư mục download về nên cá nhân hóa của opencps nếu không sẽ bị đè (hiện mặc định là docker-compose

**Comment by hoanganhkg0003** [comment]
cho mình hỏi làm sao để vào admin
